### ISSUE TITLE
GitHub Pages publishing keeps not quite working

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/annotation-aria#12]
The Travis process is running fine, but the `labs.w3.org` stuff doesn't seem to be finishing in time to get the `index.html` file updated correctly.

Here's the latest Travis log lines where the `index.html` should've been updated:
https://travis-ci.com/w3c/annotation-aria/jobs/221398844#L203-L204

However, the `index.html` doesn't include the latest content (i.e. "Referencing endnotes and footnotes" sub-header in this case).

My guess is that `raw.githack.com`--which `labs.w3.org` uses--isn't getting the most recent change in time...so it's rerunning Respec on the old content.

Not sure if there's a way to await `raw.githack.com` having the latest or to use the actual GitHub raw URL (which would be more up-to-date).

Regardless, right now the `gh-pages` branch seems to always be one commit behind--unless someone manually re-runs the Travis build.

Thoughts?

**Comment by AmeliaBR** [comment]
An alternative is to run respec directly on the Travis servers (instead of using the labs.w3.org service), using the git checkout that automatically gets sent to Travis for each build.

That's what I ended up doing for [another project I'm working on](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/blob/master/.travis.yml).

I'm pretty sure I tried using the actual raw github URL & it didn't work.

Either way, any changes to the build process should probably be discussed in the [aria-common repo](https://github.com/w3c/aria-common/). If you're having this problem, there's a chance that other ARIA specs will have it, too.

**Comment by BigBlueHat** [comment]
Thanks, @AmeliaBR! @michael-n-cooper could we consider changing the `.travis.yml` here to be similar to the one in use on Maps4HTML? https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/blob/master/.travis.yml

I think that would avoid the lag we're experience now--which requires manually rerunning Travis build scripts after each push.

Thanks!
🎩
